### ISSUE TITLE
u cant kill others but the host can 😭 😭 

### ISSUE THREAD

**Issue by Kparser246** [Milxnor/Universal-Walking-Simulator#10]

**Comment by UWUFN** [comment]
no wonder why i couldn’t kill people in medkitFN, i was so confused!

**Comment by fakebnana** [comment]
gegegdsds

**Comment by Jagger24x24** [comment]
"Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled" "Macro's disabled" "Macro's enabled"

**Comment by Kparser246** [comment]
?
