### ISSUE TITLE
Fix teams

### ISSUE THREAD

**Issue by Jyzodev** [Milxnor/Universal-Walking-Simulator#104]
I think the old teams system was good you should get it back working also make it bool so we can enable it or no and make a system for teams like nova did for example :
I want to join my friend in the same team like by using a team code like : 127.0.0.1:?Team:6969
And my friend do the same code and we are in same team i think it gonna be very difficult cuz idk but you are so smart 

And please make assault rifle ammo works

- jyzo (the guy you banned from ur discord)

**Comment by UWUFN** [comment]
where do you think nova got teams codes from
