### ISSUE TITLE
fix shooting bug, we been waiting

### ISSUE THREAD

**Issue by Kparser246** [Milxnor/Universal-Walking-Simulator#12]

**Comment by UWUFN** [comment]
OH MY GOD SHUT THE FUCK UP HOLY SHIT WE GET IT THE FUCKING ISSUE IS THERE STOP FUCKING BEGGING FOR A FUCKING FIX AND JSUT FIX IT YOURSELF SINCE YOU'RE SUCH A FUCKING SMART PERSON KPARSER SKID MEDKITFN

**Comment by Tranqlmao** [comment]
> OH MY GOD SHUT THE FUCK UP HOLY SHIT WE GET IT THE FUCKING ISSUE IS THERE STOP FUCKING BEGGING FOR A FUCKING FIX AND JSUT FIX IT YOURSELF SINCE YOU'RE SUCH A FUCKING SMART PERSON KPARSER SKID MEDKITFN
okay but fix?

**Comment by UWUFN** [comment]
I wish your family nothing but the worst.

**Comment by Kparser246** [comment]
hahahahahahahahahhahahahahahha lol lol its not like im able to see updates, so idfk

**Comment by Tranqlmao** [comment]
> I wish your family nothing but the worst.

okay but who cares about that i need fixed guns man!!!

**Comment by MarssLol** [comment]
Stfu holy fuck

**Comment by Tranqlmao** [comment]
> Stfu holy fuck

is that how fix?

**Comment by JustinKuhn1** [comment]
FIX SHOOTING BUG PENSION WEBSITE WILL BE UP SOON

**Comment by FortniteGameServer** [comment]
can yall shut up legit you a lucky to even have a gs let alone a really well working one if you have a problem with this play another build that works until the issue gets sorted don't cry about it like babies
