### ISSUE TITLE
CEASE AND DESIST LETTER

### ISSUE THREAD

**Issue by UWUFN** [Milxnor/Universal-Walking-Simulator#2]
CEASE AND DESIST LETTER

8/15/2022

Dear Grayson/Milxnor:

This CEASE AND DESIST ORDER is to inform you that your copyright infringement and intimidating actions against me has become unbearable. Such anti-social behavior is completely unacceptable and will not be tolerated in any way, shape or form. This letter is to demand that your harassment and intimidation must CEASE AND DESIST immediately. Should you continue to pursue these activities in violation of this CEASE AND DESIST ORDER, we will not hesitate to pursue further legal action against you, including, but not limited to, civil action and/or criminal complaints.
Please note that I have a right to remain free from your intimidating tactics, and we will take the responsibility upon ourselves to protect that right. Note that a copy of this letter and a record of its delivery will be stored. Note too that it is admissible as evidence in a court of law and will be used as such if need be in the future.
This CEASE AND DESIST ORDER demands that you immediately discontinue and do not at any point in the future under any circumstances do the following to me: speak to, contact, pursue, harass, attack, strike, threaten, telephone (via cellular or landline), instant message, page, fax, email, disturb my peace, keep me under surveillance, gather information about and/or block my movements at home, work, social gatherings or religious functions, as well as contact via reddit.com
Note that your behavior is a violation of Federal Criminal Statutes 47 USC 223(a)(1)(c) - Obscene or Harassing Telephone Calls in the District of Columbia or in Interstate or Foreign Communications; District of Columbia Code, Title 22, Section 504 - Threatened Assault in a Menacing Manner; Stalking
Additionally note that your behavior is a violation of US Federal Laws 18 USC Subsection 2265 Full Faith and Credit, 18 USC Subsection 2261A Interstate Stalking, 18 USC Subsection 875(c) Interstate Communications, 47 USC Subsection 223(a)(1)(c) Harassing Telephone Calls in Interstate Communications
Should you willfully choose to continue your current course of action, I will not hesitate to file a complaint with the Reddit Administration for your ongoing violations of the Criminal Laws noted previously.
This letter does not constitute exhaustive statement of my position nor is it a waiver of any of my rights and/or remedies in this and/or any other related matter.
We demand your immediate compliance, and furthermore that you confirm in writing that all volatile activity will cease immediately.
Very truly yours,
Someone special

Sent via Epic Games OG Fortnite Team.

**Comment by Jagger24x24** [comment]
ratio + dog water + my game now + we live in Afghanistan + get bombed + ratio x 17 + skull emoji + renegade raider

**Comment by UWUFN** [comment]
> ratio + dog water + my game now + we live in Afghanistan + get bombed + ratio x 17 + skull emoji + renegade raider

You are black.
