### ISSUE TITLE
S5 v5.41 crashes

### ISSUE THREAD

**Issue by DatreRSX** [Milxnor/Universal-Walking-Simulator#29]
LogCore: Warning: LIGHTWEIGHT_TIME_GUARD: FTickFunctionTask - FortWorldManager /Game/Athena/Maps/Athena_Terrain.Athena_Terrain:PersistentLevel.DO_NOT_DELETE_FortWorldManager[TickActor] took 729.63ms!

**Comment by Milxnor** [comment]
this isn't helpful
