### ISSUE TITLE
interface does not work when you start the match (you cannot interact with it)

### ISSUE THREAD

**Issue by DatreRSX** [Milxnor/Universal-Walking-Simulator#32]

**Comment by GDBOI101** [comment]
Is this only on a certain version? it seems to work fine for me.

**Comment by DatreRSX** [comment]
it happens to me a few times in different versions

**Comment by DatreRSX** [comment]
you can click the start button and start the game but you can not change the tab to start an event

**Comment by Milxnor** [comment]
idk its just u
