### ISSUE TITLE
no Chest Open Sound = no 1:1

### ISSUE THREAD

**Issue by BIGL123123** [Milxnor/Universal-Walking-Simulator#54]
no Chest Open Sound = BIGL

**Comment by BIGL123123** [comment]
https://user-images.githubusercontent.com/104046070/189047357-ada11b99-672e-4423-a2da-91d52b744546.mp4

Make it like this

**Comment by BIGL123123** [comment]
Uploading 2022-08-24 15-54-58.mp4…

Make it like that

**Comment by BIGL123123** [comment]
Noggo has a smalll penis

**Comment by BIGL123123** [comment]
![Screenshot (1645)](https://user-images.githubusercontent.com/104046070/189049300-335994be-5164-467c-9c63-4552ed78fb93.png)
Endermann

**Comment by BIGL123123** [comment]
![Screenshot (1640)](https://user-images.githubusercontent.com/104046070/189049329-bed941d8-7070-4234-9a17-2bd5a45ad0f1.png)
Endermann V2

**Comment by BIGL123123** [comment]
![Screenshot (1383)](https://user-images.githubusercontent.com/104046070/189049387-6800a43b-3917-45cd-ab70-e749eb3d8e24.png)
Gayparser

**Comment by BIGL123123** [comment]
![synchronsprecher_peter_griffin_family_guy-220x220](https://user-images.githubusercontent.com/104046070/189049780-bb9f0509-d411-4956-9959-f5d08b976fe4.jpg)

**Comment by Noggo123** [comment]
> Noggo has a smalll penis

yeah and yours doesent fucking exist
