### ISSUE TITLE
C2 S4 crashes when a player joins

### ISSUE THREAD

**Issue by CoolNiteYT** [Milxnor/Universal-Walking-Simulator#58]
No idea why , but if you're hosting c2 s4 and a player joins the server then it crashes (at least on 14.60)

I don't have the FortniteGame log file for the crash anymore sadly (I could get another log of the crash though if you need it)

**Comment by Milxnor** [comment]
not supported for a reason.

**Comment by CoolNiteYT** [comment]
> not supported for a reason.

ah ok
