### ISSUE TITLE
No Elim Text

### ISSUE THREAD

**Issue by Kparser246** [Milxnor/Universal-Walking-Simulator#60]
when killing a player, u dont see the Eliminated [PLAYER NAME] 
which feels weird

**Comment by Nightmaresuwu** [comment]
> when killing a player, u dont see the Eliminated [PLAYER NAME]
> which feels weird

It’s easy to fix lmao

**Comment by Kparser246** [comment]
well some people may not know how

**Comment by vunchas** [comment]
how'd you fix it?

**Comment by Milxnor** [comment]
it has been pushed.
