### ISSUE TITLE
19.10 crashes on inject

### ISSUE THREAD

**Issue by datrolling** [Milxnor/Universal-Walking-Simulator#73]
Project Rebootbbsaqaw.dll!GetMembersAsObjects() [C:\Users\lefishing\Documents\Universal-Walking-Simulator-master\Universal Walking Simulator\UE\structs.h:938]
Project Rebootbbsaqaw.dll!FindFunction() [C:\Users\lefishing\Documents\Universal-Walking-Simulator-master\Universal Walking Simulator\UE\structs.h:962]
Project Rebootbbsaqaw.dll!Helper::GetActorLocation() [C:\Users\lefishing\Documents\Universal-Walking-Simulator-master\Universal Walking Simulator\Gameplay\helper.h:378]
Project Rebootbbsaqaw.dll!ehehheDetour() [C:\Users\lefishing\Documents\Universal-Walking-Simulator-master\Universal Walking Simulator\hooks.h:2349]

**Comment by Milxnor** [comment]
fixed
