### ISSUE TITLE
I added Chest open sound 

### ISSUE THREAD

**Issue by BIGL123123** [Milxnor/Universal-Walking-Simulator#78]
Fuck Noggo

https://user-images.githubusercontent.com/104046070/192311679-6b5b521e-dc23-487b-b639-b4550036c7aa.mp4

**Comment by BIGL123123** [comment]
Nightmares is a SKID

**Comment by BIGL123123** [comment]
![Screenshot (2222)](https://user-images.githubusercontent.com/104046070/192312813-26f8dfa9-5a91-42b0-970e-9c4b2dc242eb.png)
hahahahahahah

**Comment by Milxnor** [comment]
ok..?
