### ISSUE TITLE
shooting no longer replicates

### ISSUE THREAD

**Issue by Kparser246** [Milxnor/Universal-Walking-Simulator#8]

**Comment by UWUFN** [comment]
nooo i was so excited for impulsefn universal skid server to finally “replicate” shooting 💔💔

**Comment by Kparser246** [comment]
bro what? 💀 impulsefn is just a hosting discord server, its been down for over a month

**Comment by Jagger24x24** [comment]
when does impulseFN universal come back 😢x3

**Comment by SpringDoesStuff** [comment]
impulsefn new and improved now supporting creative destruction gameserver when?????????

**Comment by Kparser246** [comment]
also UWUFN, stop calling me travis scott after making the apology video 😭

**Comment by UWUFN** [comment]
i didnt even kno u made an apology video

**Comment by Kparser246** [comment]
i think ur array0x nice try buddy

**Comment by Jagger24x24** [comment]
but impulsefn 😭 gameserver ;(

**Comment by Kparser246** [comment]
new impulsefn is called iconic hosting :O

**Comment by NickB-30** [comment]
MedkitMP on top

**Comment by Physics2022** [comment]
Nah ShieldMP is on the comeback

**Comment by UWUFN** [comment]
so excited!!
