### ISSUE TITLE
8.51 Event Still Doesn't Work (Check comment for more info)

### ISSUE THREAD

**Issue by RyanZuZi** [Milxnor/Universal-Walking-Simulator#88]
The event starts but it doesn't take you back up to see the volcano event. This was working in a previous commit? What happened? Also theirs a missing button under the Start Event button. There was another part if you pressed it, it would take up back up.

**Comment by LilBabyy** [comment]
I made a pull request to add back GD's fix for this

**Comment by RyanZuZi** [comment]
how can i use ur version because its getting annoying lol
